// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGI9BbVPO5fIZeW-nVFXqxDt_di14ctw',
    appId: '1:876463256323:web:e6c1f591766b5856d4ef36',
    messagingSenderId: '876463256323',
    projectId: 'clicks-57eb7',
    authDomain: 'clicks-57eb7.firebaseapp.com',
    storageBucket: 'clicks-57eb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoCP_0FuY47rUSebFj2VvbB-GrADlD-ns',
    appId: '1:876463256323:android:a779b78c76e91932d4ef36',
    messagingSenderId: '876463256323',
    projectId: 'clicks-57eb7',
    storageBucket: 'clicks-57eb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVQXs8JlePlA6U0xfd8_RxHA5gJy_N57U',
    appId: '1:876463256323:ios:316d6635a3e18233d4ef36',
    messagingSenderId: '876463256323',
    projectId: 'clicks-57eb7',
    storageBucket: 'clicks-57eb7.firebasestorage.app',
    iosBundleId: 'com.example.photographers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVQXs8JlePlA6U0xfd8_RxHA5gJy_N57U',
    appId: '1:876463256323:ios:316d6635a3e18233d4ef36',
    messagingSenderId: '876463256323',
    projectId: 'clicks-57eb7',
    storageBucket: 'clicks-57eb7.firebasestorage.app',
    iosBundleId: 'com.example.photographers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhGI9BbVPO5fIZeW-nVFXqxDt_di14ctw',
    appId: '1:876463256323:web:0d441696df1ad3d0d4ef36',
    messagingSenderId: '876463256323',
    projectId: 'clicks-57eb7',
    authDomain: 'clicks-57eb7.firebaseapp.com',
    storageBucket: 'clicks-57eb7.firebasestorage.app',
  );

}